spring.application.name=Assessment

#port
server.port=8080

#Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/assessment
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver

# ============================================================
# HIBERNATE CONFIG
# ============================================================
# Show SQL queries in console
spring.jpa.show-sql=true               

# Pretty print SQL
spring.jpa.properties.hibernate.format_sql=true 

# Auto-create/update tables
spring.jpa.hibernate.ddl-auto=update   

jwt.secret=MySuperSecureSecretKeyForJWT256BitsMinimumLength!!